# libogg_1.3.5
GIT_URL="https://github.com/xiph/ogg"
GIT_COMMIT="tags/v1.3.5"
BUILD_PROCESS=cmakebuild
CONF_FLAGS=""
VAR_INSTALL_LIBDIR=CMAKE_INSTALL_LIBDIR
VAR_INSTALL_INCDIR=CMAKE_INSTALL_INCLUDEDIR
INST_CMD=install/strip