# libwavpack_5.4.0
PKG_URL="https://www.wavpack.com/wavpack-5.4.0.tar.xz"
BUILD_PROCESS=configmake
CONF_FLAGS=""
#VAR_INSTALL_LIBDIR=CMAKE_INSTALL_LIBDIR
#VAR_INSTALL_INCDIR=CMAKE_INSTALL_INCLUDEDIR
INST_CMD=install-strip
PKG_DEPS=""
