# libvorbis_1.3.7
GIT_URL="https://github.com/xiph/vorbis"
GIT_COMMIT="tags/v1.3.7"
BUILD_PROCESS=cmakebuild
CONF_FLAGS=""
VAR_INSTALL_LIBDIR=CMAKE_INSTALL_LIBDIR
VAR_INSTALL_INCDIR=CMAKE_INSTALL_INCLUDEDIR
INST_CMD=install/strip
PKG_DEPS="moode/libogg_1.3.5"
